import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/navbar";
import { Proiversession } from "@/apis/myprovider/porivdersession";
import { ToastContainer } from "react-toastify";
import Providers from "./providerquery";
import Footer from "./footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Providers>
        <Proiversession>
        <Navbar/>
        <div>
          {children}
                    <ToastContainer />

        </div>
        <Footer/>
        </Proiversession>
        </Providers>
        </body>
    </html>
  );
}
